application: evolve-competitive-picks
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /img
  static_dir: app/img

- url: /font
  static_dir: app/font

- url: /css
  static_dir: app/css

- url: /js
  static_dir: app/js

- url: /partials
  static_dir: app/partials

- url: /.*
  static_files: app/index.html
  upload: app/index.html

libraries:
- name: webapp2
  version: "2.5.2"
